{
 "title": "PiCluster Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Network - In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "KB/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:240",
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:241",
       "field": "date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:238",
       "field": "network_rx",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Network - Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "KB/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:581",
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:582",
       "field": "date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:579",
       "field": "network_tx",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "PiCluster CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:416",
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:417",
       "field": "date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:414",
       "field": "cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "PiCluster Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:638",
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:639",
       "field": "date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:636",
       "field": "memory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "PiCluster Running Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:933",
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:934",
       "field": "date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:931",
       "field": "total_running_containers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "PiCluster Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1165",
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1166",
       "field": "date",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1163",
       "field": "disk",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "date"
    }
   ]
  }
 ]
}